stateLaws = [
   {
      "State":"ALABAMA",
      "Agency":"Federal",
      "Caller ID":"No",
      "Calling Hour Restrictions":"8:00AM - 8:00PM",
      "days":{
         7:{
            "allowed":0,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         0:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         1:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         2:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         3:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         4:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         5:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         }
      },
      "Fines":"$2,000 per infraction"
   },
   {
      "State":"ALASKA",
      "Agency":"Federal",
      "Caller ID":"No",
      "Calling Hour Restrictions":"8:00AM - 9:00PM",
      "days":{
         7:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         0:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         1:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         2:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         3:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         4:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         5:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         }
      },
      "Fines":"Up to $5,000 per infraction"
   },
   {
      "State":"ARIZONA",
      "Agency":"Federal",
      "Caller ID":"No",
      "Calling Hour Restrictions":"8:00AM - 9:00PM",
      "days":{
         7:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         0:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         1:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         2:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         3:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         4:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         5:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         }
      },
      "Fines":"Up to $1,000 per infraction"
   },
   {
      "State":"ARKANSAS",
      "Agency":"Federal",
      "Caller ID":"No",
      "Calling Hour Restrictions":"8:00AM - 9:00PM",
      "days":{
         7:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         0:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         1:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         2:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         3:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         4:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         5:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         }
      },
      "Fines":"$10,000 per infraction"
   },
   {
      "State":"CALIFORNIA",
      "Agency":"Federal",
      "Caller ID":"No",
      "Calling Hour Restrictions":"8:00AM - 9:00PM",
      "days":{
         7:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         0:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         1:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         2:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         3:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         4:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         5:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         }
      },
      "Fines":"$500 for initial infraction with $1,000 per infraction thereafter"
   },
   {
      "State":"COLORADO",
      "Agency":"State and Federal",
      "Caller ID":"No",
      "Calling Hour Restrictions":"8:00AM - 9:00PM",
      "days":{
         7:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         0:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         1:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         2:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         3:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         4:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         5:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         }
      },
      "Fines":"$2,000 per infraction"
   },
   {
      "State":"CONNECTICUT",
      "Agency":"Federal",
      "Caller ID":"No",
      "Calling Hour Restrictions":"9:00AM - 9:00PM",
      "days":{
         7:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         0:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         1:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         2:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         3:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         4:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         5:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         }
      },
      "Fines":"$5,000 per infraction"
   },
   {
      "State":"DELAWARE",
      "Agency":"Federal",
      "Caller ID":"No",
      "Calling Hour Restrictions":"8:00AM - 9:00PM",
      "days":{
         7:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         0:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         1:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         2:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         3:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         4:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         5:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         }
      },
      "Fines":"Proposed fines of $500 plus"
   },
   {
      "State":"DC",
      "Agency":"Federal",
      "Caller ID":"No",
      "Calling Hour Restrictions":"8:00AM - 9:00PM",
      "days":{
         7:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         0:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         1:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         2:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         3:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         4:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         5:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         }
      },
      "Fines":"None"
   },
   {
      "State":"FLORIDA",
      "Agency":"State and Federal",
      "Caller ID":"No",
      "Calling Hour Restrictions":"8:00AM - 9:00PM",
      "days":{
         7:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         0:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         1:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         2:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         3:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         4:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         5:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         }
      },
      "Fines":"$10,000 per infraction"
   },
   {
      "State":"GEORGIA",
      "Agency":"Federal",
      "Caller ID":"No",
      "Calling Hour Restrictions":"8:00AM - 9:00PM",
      "days":{
         7:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         0:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         1:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         2:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         3:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         4:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         5:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         }
      },
      "Fines":"$2,000 per infraction"
   },
   {
      "State":"HAWAII",
      "Agency":"Federal",
      "Caller ID":"No",
      "Calling Hour Restrictions":"8:00AM - 9:00PM",
      "days":{
         7:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         0:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         1:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         2:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         3:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         4:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         5:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         }
      },
      "Fines":"DNC Violation is Unfair/Deceptive Act"
   },
   {
      "State":"IDAHO",
      "Agency":"Federal",
      "Caller ID":"No",
      "Calling Hour Restrictions":"8:00AM - 9:00PM",
      "days":{
         7:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         0:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         1:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         2:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         3:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         4:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         5:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         }
      },
      "Fines":"$500 for initial infraction. $2,500 for second infraction. $5,000 per infraction thereafter"
   },
   {
      "State":"ILLINOIS",
      "Agency":"Federal",
      "Caller ID":"No",
      "Calling Hour Restrictions":"8:00AM - 9:00PM",
      "days":{
         7:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         0:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         1:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         2:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         3:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         4:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         5:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         }
      },
      "Fines":"$1,000 for initial infraction with up to $2,500 for each infraction thereafter"
   },
   {
      "State":"INDIANA",
      "Agency":"State and Federal",
      "Caller ID":"No",
      "Calling Hour Restrictions":"8:00AM - 9:00PM",
      "days":{
         7:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         0:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         1:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         2:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         3:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         4:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         5:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         }
      },
      "Fines":"$10,000 for initial infraction and $25,000 per infraction thereafter"
   },
   {
      "State":"IOWA",
      "Agency":"Federal",
      "Caller ID":"No",
      "Calling Hour Restrictions":"8:00AM - 9:00PM",
      "days":{
         7:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         0:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         1:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         2:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         3:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         4:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         5:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         }
      },
      "Fines":"Proposed $100 to $2,000"
   },
   {
      "State":"KANSAS",
      "Agency":"Federal",
      "Caller ID":"No",
      "Calling Hour Restrictions":"8:00AM - 9:00PM",
      "days":{
         7:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         0:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         1:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         2:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         3:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         4:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         5:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         }
      },
      "Fines":"Up to $10,000 per infraction"
   },
   {
      "State":"KENTUCKY",
      "Agency":"Federal",
      "Caller ID":"No",
      "Calling Hour Restrictions":"10:00AM - 9:00PM",
      "days":{
         7:{
            "allowed":1,
            "start_full":"10:00",
            "end_full":"21:00"
         },
         0:{
            "allowed":1,
            "start_full":"10:00",
            "end_full":"21:00"
         },
         1:{
            "allowed":1,
            "start_full":"10:00",
            "end_full":"21:00"
         },
         2:{
            "allowed":1,
            "start_full":"10:00",
            "end_full":"21:00"
         },
         3:{
            "allowed":1,
            "start_full":"10:00",
            "end_full":"21:00"
         },
         4:{
            "allowed":1,
            "start_full":"10:00",
            "end_full":"21:00"
         },
         5:{
            "allowed":1,
            "start_full":"10:00",
            "end_full":"21:00"
         }
      },
      "Fines":"Up to $10,000 per infraction depending of violation"
   },
   {
      "State":"LOUISIANA",
      "Agency":"State and Federal",
      "Caller ID":"No",
      "Calling Hour Restrictions":"8:00AM - 8:00PM",
      "days":{
         7:{
            "allowed":0,
            "start_full":"08:00",
            "end_full":"20:00"
         },
         0:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"20:00"
         },
         1:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"20:00"
         },
         2:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"20:00"
         },
         3:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"20:00"
         },
         4:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"20:00"
         },
         5:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"20:00"
         }
      },
      "Fines":"$1,500 per infraction and $3,000 per infraction when consumer over the age of sixty-five (65)"
   },
   {
      "State":"MAINE",
      "Agency":"Federal",
      "Caller ID":"No",
      "Calling Hour Restrictions":"8:00AM - 9:00PM",
      "days":{
         7:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         0:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         1:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         2:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         3:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         4:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         5:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         }
      },
      "Fines":"$500 per infraction"
   },
   {
      "State":"MARYLAND",
      "Agency":"Federal",
      "Caller ID":"No",
      "Calling Hour Restrictions":"8:00AM - 9:00PM",
      "days":{
         7:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         0:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         1:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         2:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         3:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         4:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         5:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         }
      },
      "Fines":"$1,000 for initial infraction and up to $5,000 per infraction thereafter"
   },
   {
      "State":"MASSACHUSETTS",
      "Agency":"State and Federal",
      "Caller ID":"No",
      "Calling Hour Restrictions":"8:00AM - 8:00PM",
      "days":{
         7:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         0:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         1:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         2:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         3:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         4:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         5:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         }
      },
      "Fines":"Up to $5,000.00 per infraction"
   },
   {
      "State":"MICHIGAN",
      "Agency":"Federal",
      "Caller ID":"No",
      "Calling Hour Restrictions":"9:00AM - 9:00PM",
      "days":{
         7:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         0:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         1:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         2:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         3:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         4:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         5:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         }
      },
      "Fines":"A misdemeanor with fines ranging from six (6) months imprisonment and/or $500.00 per infraction"
   },
   {
      "State":"MINNESOTA",
      "Agency":"Federal",
      "Caller ID":"No",
      "Calling Hour Restrictions":"9:00AM - 9:00PM",
      "days":{
         7:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         0:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         1:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         2:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         3:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         4:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         5:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         }
      },
      "Fines":"$1,000 per infraction"
   },
   {
      "State":"MISSISSIPPI",
      "Agency":"State and Federal",
      "Caller ID":"No",
      "Calling Hour Restrictions":"8:00AM - 8:00PM",
      "days":{
         7:{
            "allowed":0,
            "start_full":"08:00",
            "end_full":"20:00"
         },
         0:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"20:00"
         },
         1:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"20:00"
         },
         2:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"20:00"
         },
         3:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"20:00"
         },
         4:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"20:00"
         },
         5:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"20:00"
         }
      },
      "Fines":"$5,000 per infraction"
   },
   {
      "State":"MISSOURI",
      "Agency":"State and Federal",
      "Caller ID":"No",
      "Calling Hour Restrictions":"8:00AM - 9:00PM",
      "days":{
         7:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         0:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         1:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         2:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         3:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         4:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         5:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         }
      },
      "Fines":"$5,000 per infraction"
   },
   {
      "State":"MONTANA",
      "Agency":"Federal",
      "Caller ID":"No",
      "Calling Hour Restrictions":"8:00AM - 9:00PM",
      "days":{
         7:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         0:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         1:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         2:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         3:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         4:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         5:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         }
      },
      "Fines":"$5,000 per knowing infraction"
   },
   {
      "State":"NEBRASKA",
      "Agency":"Federal",
      "Caller ID":"No",
      "Calling Hour Restrictions":"8:00AM - 9:00PM",
      "days":{
         7:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         0:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         1:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         2:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         3:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         4:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         5:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         }
      },
      "Fines":"Proposed $2,000 per infraction"
   },
   {
      "State":"NEVADA",
      "Agency":"Federal",
      "Caller ID":"No",
      "Calling Hour Restrictions":"9:00AM - 8:00PM",
      "days":{
         7:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"20:00"
         },
         0:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"20:00"
         },
         1:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"20:00"
         },
         2:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"20:00"
         },
         3:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"20:00"
         },
         4:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"20:00"
         },
         5:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"20:00"
         }
      },
      "Fines":"Up to $10,000 per infraction"
   },
   {
      "State":"NEW HAMPSHIRE",
      "Agency":"Federal",
      "Caller ID":"No",
      "Calling Hour Restrictions":"8:00AM - 9:00PM",
      "days":{
         7:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         0:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         1:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         2:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         3:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         4:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         5:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         }
      },
      "Fines":"Proposed $2,000 per infraction"
   },
   {
      "State":"NEW JERSEY",
      "Agency":"Federal",
      "Caller ID":"No",
      "Calling Hour Restrictions":"8:00AM - 9:00PM",
      "days":{
         7:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         0:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         1:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         2:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         3:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         4:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         5:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         }
      },
      "Fines":"$10,000 for initial infraction and $20,000 per infraction thereafter"
   },
   {
      "State":"NEW MEXICO",
      "Agency":"Federal",
      "Caller ID":"No",
      "Calling Hour Restrictions":"9:00AM - 9:00PM",
      "days":{
         7:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         0:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         1:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         2:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         3:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         4:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         5:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         }
      },
      "Fines":"$500 per infraction"
   },
   {
      "State":"NEW YORK",
      "Agency":"Federal",
      "Caller ID":"No",
      "Calling Hour Restrictions":"8:00AM - 9:00PM",
      "days":{
         7:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         0:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         1:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         2:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         3:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         4:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         5:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         }
      },
      "Fines":"$11,000 per infraction"
   },
   {
      "State":"NORTH CAROLINA",
      "Agency":"Federal",
      "Caller ID":"No",
      "Calling Hour Restrictions":"8:00AM - 9:00PM",
      "days":{
         7:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         0:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         1:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         2:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         3:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         4:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         5:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         }
      },
      "Fines":"None"
   },
   {
      "State":"NORTH DAKOTA",
      "Agency":"Federal",
      "Caller ID":"No",
      "Calling Hour Restrictions":"8:00AM - 9:00PM",
      "days":{
         7:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         0:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         1:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         2:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         3:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         4:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         5:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         }
      },
      "Fines":"$2,000 per infraction"
   },
   {
      "State":"OHIO",
      "Agency":"Federal",
      "Caller ID":"No",
      "Calling Hour Restrictions":"8:00AM - 9:00PM",
      "days":{
         7:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         0:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         1:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         2:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         3:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         4:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         5:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         }
      },
      "Fines":"As Per Federal Rules"
   },
   {
      "State":"OKLAHOMA",
      "Agency":"State and Federal",
      "Caller ID":"No",
      "Calling Hour Restrictions":"8:00AM - 9:00PM",
      "days":{
         7:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         0:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         1:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         2:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         3:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         4:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         5:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         }
      },
      "Fines":"Between $500 and $1,500 per infraction"
   },
   {
      "State":"OREGON",
      "Agency":"Federal",
      "Caller ID":"No",
      "Calling Hour Restrictions":"9:00AM - 9:00PM",
      "days":{
         7:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         0:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         1:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         2:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         3:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         4:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         5:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         }
      },
      "Fines":"Up to $25,000 per infraction"
   },
   {
      "State":"PENNSYLVANIA",
      "Agency":"State and Federal",
      "Caller ID":"Yes",
      "Calling Hour Restrictions":"8:00AM - 9:00PM",
      "days":{
         7:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         0:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         1:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         2:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         3:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         4:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         5:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         }
      },
      "Fines":"$1,000 per infraction; $3,000 if involving consumer age 60 or older"
   },
   {
      "State":"RHODE ISLAND",
      "Agency":"Federal",
      "Caller ID":"No",
      "Calling Hour Restrictions":"9:00AM - 6:00PM and 10:00AM - 5:00PM on Saturdays; No calls on Sundays",
      "days":{
         7:{
            "allowed":0,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         0:{
            "allowed":1,
            "start_full":"09:00",
            "end_full":"18:00"
         },
         1:{
            "allowed":1,
            "start_full":"09:00",
            "end_full":"18:00"
         },
         2:{
            "allowed":1,
            "start_full":"09:00",
            "end_full":"18:00"
         },
         3:{
            "allowed":1,
            "start_full":"09:00",
            "end_full":"18:00"
         },
         4:{
            "allowed":1,
            "start_full":"09:00",
            "end_full":"18:00"
         },
         5:{
            "allowed":1,
            "start_full":"10:00",
            "end_full":"17:00"
         }
      },
      "Fines":"Proposed $500 for first infraction with $1,000 for each subsequent infraction"
   },
   {
      "State":"SOUTH CAROLINA",
      "Agency":"Federal",
      "Caller ID":"No",
      "Calling Hour Restrictions":"8:00AM - 9:00PM",
      "days":{
         7:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         0:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         1:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         2:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         3:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         4:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         5:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         }
      },
      "Fines":"Proposed $500 for first infraction with $2,500 for second infraction and $5,000 for each subsequent infraction"
   },
   {
      "State":"SOUTH DAKOTA",
      "Agency":"Federal",
      "Caller ID":"No",
      "Calling Hour Restrictions":"9:00AM - 9:00PM",
      "days":{
         7:{
            "allowed":0,
            "start_full":"09:00",
            "end_full":"21:00"
         },
         0:{
            "allowed":1,
            "start_full":"09:00",
            "end_full":"21:00"
         },
         1:{
            "allowed":1,
            "start_full":"09:00",
            "end_full":"21:00"
         },
         2:{
            "allowed":1,
            "start_full":"09:00",
            "end_full":"21:00"
         },
         3:{
            "allowed":1,
            "start_full":"09:00",
            "end_full":"21:00"
         },
         4:{
            "allowed":1,
            "start_full":"09:00",
            "end_full":"21:00"
         },
         5:{
            "allowed":1,
            "start_full":"09:00",
            "end_full":"21:00"
         }
      },
      "Fines":"$5,000 per infraction"
   },
   {
      "State":"TENNESSEE",
      "Agency":"State and Federal",
      "Caller ID":"No",
      "Calling Hour Restrictions":"8:00AM - 9:00PM",
      "days":{
         7:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         0:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         1:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         2:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         3:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         4:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         5:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         }
      },
      "Fines":"$2,000 per infraction"
   },
   {
      "State":"TEXAS",
      "Agency":"State and Federal",
      "Caller ID":"No",
      "Calling Hour Restrictions":"9:00AM - 9:00PM & 12:00PM - 9:00PM on Sundays",
      "days":{
         7:{
            "allowed":1,
            "start_full":"12:00",
            "end_full":"21:00"
         },
         0:{
            "allowed":1,
            "start_full":"09:00",
            "end_full":"21:00"
         },
         1:{
            "allowed":1,
            "start_full":"09:00",
            "end_full":"21:00"
         },
         2:{
            "allowed":1,
            "start_full":"09:00",
            "end_full":"21:00"
         },
         3:{
            "allowed":1,
            "start_full":"09:00",
            "end_full":"21:00"
         },
         4:{
            "allowed":1,
            "start_full":"09:00",
            "end_full":"21:00"
         },
         5:{
            "allowed":1,
            "start_full":"09:00",
            "end_full":"21:00"
         }
      },
      "Fines":"$1,000 per infraction, but $3,000 per infraction if determined solicitor willfully violated the law"
   },
   {
      "State":"UTAH",
      "Agency":"Federal",
      "Caller ID":"No",
      "Calling Hour Restrictions":"8:00AM - 9:00PM; No Calls Sundays or Legal Holidays",
      "days":{
         7:{
            "allowed":0,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         0:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         1:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         2:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         3:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         4:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         5:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         }
      },
      "Fines":"$2,500 per infraction"
   },
   {
      "State":"VERMONT",
      "Agency":"Federal",
      "Caller ID":"No",
      "Calling Hour Restrictions":"8:00AM - 9:00PM",
      "days":{
         7:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         0:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         1:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         2:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         3:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         4:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         5:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         }
      },
      "Fines":"$500 for first infraction with $1,000 for each subsequent infraction"
   },
   {
      "State":"VIRGINIA",
      "Agency":"Federal",
      "Caller ID":"No",
      "Calling Hour Restrictions":"8:00AM - 9:00PM",
      "days":{
         7:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         0:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         1:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         2:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         3:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         4:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         5:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         }
      },
      "Fines":"None"
   },
   {
      "State":"WASHINGTON",
      "Agency":"Federal",
      "Caller ID":"No",
      "Calling Hour Restrictions":"8:00AM - 9:00PM",
      "days":{
         7:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         0:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         1:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         2:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         3:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         4:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         5:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         }
      },
      "Fines":"None"
   },
   {
      "State":"WEST VIRGINIA",
      "Agency":"Federal",
      "Caller ID":"No",
      "Calling Hour Restrictions":"8:00AM - 9:00PM",
      "days":{
         7:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         0:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         1:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         2:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         3:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         4:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         5:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         }
      },
      "Fines":"None"
   },
   {
      "State":"WISCONSIN",
      "Agency":"State and Federal",
      "Caller ID":"No",
      "Calling Hour Restrictions":"8:00AM - 9:00PM",
      "days":{
         7:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         0:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         1:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         2:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         3:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         4:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         },
         5:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"21:00"
         }
      },
      "Fines":"Fines range from $1,000 - $10,000 per infraction"
   },
   {
      "State":"WYOMING",
      "Agency":"State and Federal",
      "Caller ID":"Yes",
      "Calling Hour Restrictions":"8:00AM to 8:00PM",
      "days":{
         7:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"20:00"
         },
         0:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"20:00"
         },
         1:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"20:00"
         },
         2:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"20:00"
         },
         3:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"20:00"
         },
         4:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"20:00"
         },
         5:{
            "allowed":1,
            "start_full":"08:00",
            "end_full":"20:00"
         }
      },
      "Fines":"$2,500 per infraction"
   }
]